language: ruby
rvm:
- '2.3.1'
sudo: false
cache: bundler
addons:
  postgresql: '9.4'
before_install:
- rvm @global do gem uninstall bundler -a -x
- rvm @global do gem install bundler -v 1.15.4
bundler_args: --no-deployment
before_script: bundle exec rake spec:setup
install: bin/setup
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/46abb9c5f1f009b6a699
    on_success: change
    on_failure: always
    on_start: never
