language: ruby
rvm:
- '2.3.1'
sudo: false
cache: bundler
addons:
  postgresql: '9.4'
before_install:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
before_script: bundle exec rake spec:setup
after_script: bundle exec codeclimate-test-reporter
