---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Deployment Remove Error
    name: hawkular_deployment_remove.error
    inherits: 
    description: 
  fields:
  - rel4:
      value: "/System/event_handlers/event_action_policy?target=middleware_server&policy_event=middleware_deployment_remove_error&param="
