---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Deployment Success
    name: hawkular_deployment.ok
    inherits: 
    description: 
  fields:
  - rel4:
      value: "/System/event_handlers/event_action_refresh?target=ems"
  - rel5:
      value: "/System/event_handlers/event_action_policy?target=middleware_server&policy_event=middleware_deployment_ok&param="
